#!/usr/bin/env bash
# Reproducible development environment setup for Monica by Avalonia (Linux desktop vault).
#
# Installs the .NET 10 SDK, PowerShell 7, the Linux desktop / Avalonia runtime
# dependencies, and builds + deploys the native MDBX UniFFI bridge that the vault
# backend loads at runtime. Safe to run repeatedly (idempotent).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOLUTION_DIR="$REPO_ROOT/monica by avalonia"

DOTNET_DIR="$HOME/.dotnet"
PWSH_DIR="$HOME/.powershell"
NATIVE_DIR="$HOME/.monica-native"
MDBX_DIR="$HOME/.monica-mdbx"

# The checked-in C# UniFFI bindings (src/Monica.Platform/Mdbx/Generated/mdbx_ffi.cs)
# were generated by uniffi-bindgen-cs v0.10.0+v0.29.4 (UniFFI contract version 29).
# This is the upstream MDBX commit that produced them ("Expose MDBX UniFFI bindings
# for C# clients"); it pins uniffi = "=0.29.4" and still exposes the attachment API on
# the vault object, so the native ABI matches the bindings exactly.
MDBX_REPO="https://github.com/Monica-Pass/Mdbx.git"
MDBX_COMMIT="fdf3382"

echo ">> Installing system packages (libsecret, X11 / Avalonia runtime deps)"
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends \
  ca-certificates curl git \
  libsecret-1-0 libsecret-1-dev \
  libx11-6 libx11-dev libice6 libsm6 libfontconfig1 libglib2.0-0 \
  libnotify4 libgdiplus \
  xvfb x11-utils

echo ">> Installing .NET SDK 10.0"
if ! "$DOTNET_DIR/dotnet" --list-sdks 2>/dev/null | grep -q '^10\.'; then
  curl -sSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh
  bash /tmp/dotnet-install.sh --channel 10.0 --install-dir "$DOTNET_DIR"
fi
export DOTNET_ROOT="$DOTNET_DIR"
export PATH="$DOTNET_DIR:$PATH"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1

echo ">> Installing PowerShell 7 (unified verification / packaging scripts)"
if ! command -v pwsh >/dev/null 2>&1; then
  PWSH_VER=7.4.6
  curl -sSL "https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VER}/powershell-${PWSH_VER}-linux-x64.tar.gz" -o /tmp/pwsh.tar.gz
  mkdir -p "$PWSH_DIR"
  tar zxf /tmp/pwsh.tar.gz -C "$PWSH_DIR"
  chmod +x "$PWSH_DIR/pwsh"
  sudo ln -sf "$PWSH_DIR/pwsh" /usr/local/bin/pwsh
fi

echo ">> Ensuring a recent Rust toolchain (edition2024 needs >= 1.85)"
if command -v rustup >/dev/null 2>&1; then
  rustup update stable
  rustup default stable
fi

echo ">> Building the native MDBX UniFFI bridge (libmdbx_ffi.so)"
if [ ! -d "$MDBX_DIR/.git" ]; then
  git clone "$MDBX_REPO" "$MDBX_DIR"
fi
git -C "$MDBX_DIR" fetch origin
git -C "$MDBX_DIR" checkout -q "$MDBX_COMMIT"
( cd "$MDBX_DIR" && cargo build -p mdbx-ffi --release )

echo ">> Deploying the native library onto the loader path"
mkdir -p "$NATIVE_DIR"
cp -f "$MDBX_DIR/target/release/libmdbx_ffi.so" "$NATIVE_DIR/libmdbx_ffi.so"
# The availability probe uses NativeLibrary.TryLoad("mdbx_ffi"), which on Linux does NOT
# apply the lib*.so naming convention, so also expose a bare-named copy that dlopen finds
# via LD_LIBRARY_PATH.
cp -f "$MDBX_DIR/target/release/libmdbx_ffi.so" "$NATIVE_DIR/mdbx_ffi"

echo ">> Restoring and building the solution (Release)"
"$DOTNET_DIR/dotnet" restore "$SOLUTION_DIR/Monica.slnx"
LD_LIBRARY_PATH="$NATIVE_DIR:${LD_LIBRARY_PATH:-}" \
  "$DOTNET_DIR/dotnet" build "$SOLUTION_DIR/Monica.slnx" --configuration Release --no-restore

echo ">> Copying the native library next to build outputs"
for proj in "src/Monica.App" "tests/Monica.Tests" "tests/Monica.UiTests"; do
  out="$SOLUTION_DIR/$proj/bin/Release/net10.0"
  if [ -d "$out" ]; then
    cp -f "$NATIVE_DIR/libmdbx_ffi.so" "$out/libmdbx_ffi.so"
    cp -f "$NATIVE_DIR/mdbx_ffi" "$out/mdbx_ffi"
  fi
done

echo ">> Persisting environment variables for interactive shells"
if ! grep -q 'MONICA ENV' "$HOME/.bashrc" 2>/dev/null; then
  cat >> "$HOME/.bashrc" <<EOF

# --- MONICA ENV ---
export DOTNET_ROOT="$DOTNET_DIR"
export PATH="$DOTNET_DIR:\$PATH"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1
export LD_LIBRARY_PATH="$NATIVE_DIR:\${LD_LIBRARY_PATH:-}"
# --- /MONICA ENV ---
EOF
fi

echo ">> Monica development environment is ready."
